---
apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-app-blue
spec:
  replicas: 8
  selector:
    app: demo-app
    version: blue
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
        version: blue
    spec:
      containers:
      - name: demo-app
        image: lmarsden/demo-app:blue
        ports:
        - containerPort: 80
