---
apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-app-green
spec:
  replicas: 8
  selector:
    app: demo-app
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: lmarsden/demo-app:green
        ports:
        - containerPort: 80
