---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    name: demo-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    name: demo-app
