---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: demo-app
spec:
  replicas: 8
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: lmarsden/demo-app:blue
        ports:
        - containerPort: 80
