version: '2'
services:
  web:
    build: .
    ports:
     - "80:80"
    volumes:
     - .:/var/www/html/
    depends_on:
     - psql
  psql:
    image: postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: password
